# _config.yml

# Title and description
title: HTB Certified Penetration Testing Specialist
description: Modules for penetration testing and cybersecurity

# Theme for styling
theme: minima
markdown: kramdown

# Base URL settings
baseurl: ""  # Set to subfolder if needed, e.g., "/HTB-CPTS"
url: "https://oxapavan.github.io/HTB-Penetration-testing"  # Update to your GitHub Pages URL

# Navigation settings for files in directories
collections:
  academy:
    output: true
    permalink: /academy/:path/

# Optional plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Exclude items if needed
exclude:
  - README.md
